### ISSUE TITLE
getting wrong answer for overall Mhat...

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#167]
...tracking down the problem.

**Comment by ddalthorp** [comment]
Focusing on bats, visibility classes RP, M, D. Compare median estimated (and CI) with actual parameter values.

pk estimation looks right...using /inst/extdata/windRP/SE_trials.csv with p ~ Visibility and k ~ 1 as model. 
p: actual = c(0.6, 0.3, 0.13), fitted = c(0.63, 0.32, 0.10) <-- all actuals well w/in 90% CI
k: actual = c(0.75, 0.7, 0.65), fitted = c(0.68, 0.68)

cp estimation somewhat right...using /inst/extdata/windRP/CP_trials.csv with p ~ Visibility and k ~ 1 as model. 
l: actual = c(0.6931472, 1.609438, 1.94591), fitted = c(0.90766, 1.75136, 1.69657)
CIs: 
   RP (0.65865, 1.15667) <-- barely includes 0.69
   M (1.50342, 1.9993) <-- comfortably includes 1.61
   D (1.44559, 1.94756) <-- barely include 1.946

s: actual = c(1.25, 1.25, 1.25), fitted = c(1.13288, 1.13288, 1.13288) <-- actuals barely in 90% CI = 1.26
r[3]: 
actual = c(0.499071, 0.7030888, 0.7617001),
fitted = c(0.56, 0.7513, 0.7412) [based on median l and s]

**Comment by ddalthorp** [comment]
For g on RP:
Actual aggregate detection probability for bats in the data file = 181/4000 = 0.0425 [based on knowing the right answer and not relying on field trials]

Very rough guesstimates:
Back of envelope estimator (fitted): r * dwp * p = 0.56 * 0.18 * 0.63 = 0.063
Back of envelope estimator (actual):  r * dwp * p = .5  * .18 * .6 = 0.054

**Comment by DAPPERstats** [comment]
is the issue that k is the wrong scale still?

**Comment by ddalthorp** [comment]
I don't think so. 

It does look like the CP parameters that were used to generate the carcass search data don't match the parameters used to generate field trials. That could make a big difference! 

We changed the CP parameters at the last minute and apparently the changes in the generating code didn't go deep enough or we didn't use a clean R session to generate something or...in any case, I'll regenerate the data and run models again.

**Comment by ddalthorp** [comment]
btw...is k on the wrong scale still?

**Comment by ddalthorp** [comment]
fixed the data set...answers still _look_ questionable on first glance, but, w/ a closer look, they seem just right. True M is barely inside the lower bound of the 95% interval for Mhat [which raises the question], and true r * p is just outside the upper bound of the 95% interval for fitted(r) * fitted(p) [which neatly resolves it].

**Comment by DAPPERstats** [comment]
yeah, i haven't fixed that k code yet. 

I'm digging into it now to see what's up, although I could definitely use you or @madsenl 's eyes on it, too. 

From a first look, I think I need to remove the `alogit` on line 340:

```
  cellTable_k <- round(alogit(cellTable_k), 5)
```
should be
```
  cellTable_k <- round(cellTable_k, 5)
```

and on line 840:

```
      sim_k <- as.matrix(alogit(sim_beta[ , which_beta_k] %*% t(cellMM_k)))
```
should be
```
      sim_k <- as.matrix(sim_beta[ , which_beta_k] %*% t(cellMM_k))
```
right?

Am I missing any other changes and are those changes correct?

**Comment by DAPPERstats** [comment]
strike that on those edits, it was actually that i wasn't accounting for the fact that the fixed k values were getting pasted as un-transformed values onto the parameter vector that came out of optim, which has parameter values (including k if fitted, not fixed) on the logit scale (hence the alogit on line 340). 
so it was actually that i needed to logit transform the fixed k value before pasting it onto the parameter vector, so fixed k can be handled as if it was a fitted k.

there was also another possible bug with the input to the optim function being called betaInit instead of beta, although it's possible that R's fuzzy matching magic actually meant it wasn't causing any problems.

in any case, i've gone back and side-by-sided the current `pkm` function with lisa's original `pkEst1` function and I get the same answers, so that's promising!! it's possible there are still some bugs in there, so please let me know if anything seems off still, but i think the k scale issue is addressed now?

**Comment by ddalthorp** [comment]
I don't think I noticed any problems with the scale of fixed k other than what we discussed earlier. I haven't checked carefully today, but it seemed like was an easy fix, and it looks like you addressed it. I'll consider it closed (but keep it in the back of my mind as I start pushing the app testing harder).
